import { VisualizationData } from './types';

/**
 * Load NPZ files generated by TokEval and convert them to JSON
 */
export const loadMetricsFile = async (file: File): Promise<VisualizationData> => {
  // In a real implementation, this would use a library like jszip or nippy
  // to decompress and parse NPZ files. For now, we'll handle JSON.
  // NPZ support requires additional dependencies.
  
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const content = e.target?.result as string;
        const data = JSON.parse(content);
        resolve(data);
      } catch (error) {
        reject(new Error('Failed to parse visualization file'));
      }
    };
    reader.onerror = () => reject(new Error('Failed to read file'));
    reader.readAsText(file);
  });
};

/**
 * Extract available tokenizers from metrics data
 */
export const extractTokenizers = (data: VisualizationData): string[] => {
  const tokenizers = new Set<string>();
  if (data.metrics) {
    Object.keys(data.metrics).forEach((key) => {
      // Assuming key format: "tokenizer_metric_lang" or similar
      const parts = key.split('_');
      if (parts.length > 0) {
        tokenizers.add(parts[0]);
      }
    });
  }
  return Array.from(tokenizers);
};

/**
 * Extract available metrics from metrics data
 */
export const extractMetrics = (data: VisualizationData): string[] => {
  const metrics = new Set<string>();
  if (data.metrics) {
    Object.keys(data.metrics).forEach((key) => {
      metrics.add(key);
    });
  }
  return Array.from(metrics);
};

/**
 * Extract available languages from metrics data
 */
export const extractLanguages = (data: VisualizationData): string[] => {
  const languages = new Set<string>();
  if (data.metrics) {
    Object.keys(data.metrics).forEach((key) => {
      const parts = key.split('_');
      if (parts.length >= 3) {
        languages.add(parts[parts.length - 1]);
      }
    });
  }
  return Array.from(languages);
};

/**
 * Save visualization configuration to JSON
 */
export const saveVisualization = (data: VisualizationData, filename: string) => {
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
};
